// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Overview: typeof import('./src/components/overview.vue')['default']
    Overview2: typeof import('./src/components/overview2.vue')['default']
    Pageindex: typeof import('./src/components/pageindex.vue')['default']
    Path: typeof import('./src/components/Path.vue')['default']
    Property: typeof import('./src/components/property.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Showallconnect: typeof import('./src/components/showallconnect.vue')['default']
    Showerr: typeof import('./src/components/showerr.vue')['default']
    Showproperty1: typeof import('./src/components/showproperty1.vue')['default']
    Showproperty2: typeof import('./src/components/showproperty2.vue')['default']
    Showproperty3: typeof import('./src/components/showproperty3.vue')['default']
    Showproperty4: typeof import('./src/components/showproperty4.vue')['default']
    Showproperty5: typeof import('./src/components/showproperty5.vue')['default']
    Showproperty6: typeof import('./src/components/showproperty6.vue')['default']
    Showresource: typeof import('./src/components/showresource.vue')['default']
  }
}
